services:

  # Frontend & Nginx Proxy
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - spring
    networks:
      - app_network

  # Spring Boot Backend
  spring:
    build:
      context: ./spring
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app_network
    # Espera a que MariaDB esté disponible antes de arrancar
    # Spring Boot reintentará la conexión si falla al inicio
    restart: on-failure
    volumes:
      - ./spring/logs:/app/logs

  # MariaDB Database
  db:
    image: mariadb:10.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  # Node build tool (manual)
  node:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    networks:
      - app_network
    profiles:
      - tools   # Solo se activa si se llama explícitamente — no interfiere con 'up'



volumes:
  db_data:

networks:
  app_network: