services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app_network

  php:
    build: ./php
    volumes:
      - ./php:/var/www/html
    env_file:
      - .env
    networks:
      - app_network

  db:
    image: mariadb:10.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tower_of_wonder
      MYSQL_USER: admin_tow_bbdd
      MYSQL_PASSWORD: 7kr3L1UBDWgcvgY
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network: